name: GenDocsGPT

run-name: ${{ github.actor }} is generating API docs

on:
  push:
    branches:
      - main
      - master

jobs:
  genDocsGPT:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      - name: Install pip
        run: python3 -m pip install --upgrade pip
      
      - name: Install and run genDocsGPT
        run: |
          python3 -m pip install --upgrade genDocsGPT
          python3 -m genDocsGPT -v -m ./models -a ./gin -o api.md -t ${{ secrets.ChatGPT_API_KEY}} --gpt_model gpt-3.5-turbo

      - name: Create pull request with docs generated
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${{ github.actor }}@genDocsGPT.com"
          git config --global user.name "${{ github.actor }}"
          git checkout -b docs-generated-by-genDocsGPT-${{ github.run_id }}
          git add .
          git commit -m "chore: API Documenation generated by genDocsGPT"
          git push -u origin docs-generated-by-genDocsGPT-${{ github.run_id }}
          gh pr create --title "API Docs generated" --body "Pull request created by genDocsGPT GitHub Action"
